using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using AwesomeAssertions;
using Oocx.TfPlan2Md.CoverageEnforcer;
using Oocx.TfPlan2Md.Tests.TestData;
using TUnit.Core;

namespace Oocx.TfPlan2Md.Tests.Workflows;

/// <summary>
/// End-to-end tests for the coverage enforcer entry point.
/// </summary>
public class CoverageEnforcerProgramTests
{
    /// <summary>
    /// Verifies successful enforcement writes summary output and returns zero.
    /// </summary>
    [Test]
    public async Task Program_WithPassingThresholds_ReturnsZero()
    {
        var reportPath = GetCoveragePath("cobertura-sample.xml");
        var summaryPath = GetTempPath("coverage-summary.md");

        var exitCode = await InvokeProgramAsync([
            "--report",
            reportPath,
            "--line-threshold",
            "80",
            "--branch-threshold",
            "70",
            "--summary-output",
            summaryPath
        ]);

        exitCode.Should().Be(0);
        File.Exists(summaryPath).Should().BeTrue();

        await Task.CompletedTask;
    }

    /// <summary>
    /// Verifies failing thresholds return a non-zero exit code when override is disabled.
    /// </summary>
    [Test]
    public async Task Program_WithFailingThresholds_ReturnsOne()
    {
        var reportPath = GetCoveragePath("cobertura-sample.xml");

        var exitCode = await InvokeProgramAsync([
            "--report",
            reportPath,
            "--line-threshold",
            "99",
            "--branch-threshold",
            "99"
        ]);

        exitCode.Should().Be(1);

        await Task.CompletedTask;
    }

    /// <summary>
    /// Verifies override allows passing exit code even when thresholds are not met.
    /// </summary>
    [Test]
    public async Task Program_WithOverrideActive_ReturnsZero()
    {
        var reportPath = GetCoveragePath("cobertura-sample.xml");

        var exitCode = await InvokeProgramAsync([
            "--report",
            reportPath,
            "--line-threshold",
            "99",
            "--branch-threshold",
            "99",
            "--override-active",
            "true"
        ]);

        exitCode.Should().Be(0);

        await Task.CompletedTask;
    }

    /// <summary>
    /// Verifies history output requires a commit SHA and returns error when missing.
    /// </summary>
    [Test]
    public async Task Program_WithHistoryOutputWithoutCommit_ReturnsTwo()
    {
        var reportPath = GetCoveragePath("cobertura-sample.xml");
        var historyPath = GetTempPath("coverage-history.json");

        var exitCode = await InvokeProgramAsync([
            "--report",
            reportPath,
            "--line-threshold",
            "80",
            "--branch-threshold",
            "70",
            "--history-output",
            historyPath
        ]);

        exitCode.Should().Be(2);

        await Task.CompletedTask;
    }

    /// <summary>
    /// Invokes the coverage enforcer entry point.
    /// </summary>
    /// <param name="args">Arguments passed to the tool.</param>
    /// <returns>Exit code from the entry point.</returns>
    [SuppressMessage("Major Code Smell", "S3011", Justification = "Entry point is generated by top-level statements and accessed via reflection for tests.")]
    private static async Task<int> InvokeProgramAsync(string[] args)
    {
        var entryPoint = typeof(CoberturaCoverageParser).Assembly.EntryPoint;
        entryPoint.Should().NotBeNull("Coverage enforcer entry point should be available");

        var result = entryPoint!.Invoke(null, new object?[] { args });
        return result switch
        {
            Task<int> task => await task,
            int code => code,
            Task task => await task.ContinueWith(_ => 0),
            _ => throw new InvalidOperationException("Unexpected entry point return type.")
        };
    }

    /// <summary>
    /// Builds the absolute path for a coverage test data file.
    /// </summary>
    /// <param name="fileName">Coverage test data file name.</param>
    /// <returns>Absolute path to the test data file.</returns>
    private static string GetCoveragePath(string fileName)
    {
        return Path.Combine(DemoPaths.RepositoryRoot, "src", "tests", "Oocx.TfPlan2Md.TUnit", "TestData", "Coverage", fileName);
    }

    /// <summary>
    /// Builds a temporary path under the repository .tmp directory.
    /// </summary>
    /// <param name="fileName">File name for the temp output.</param>
    /// <returns>Absolute path to the temp file.</returns>
    private static string GetTempPath(string fileName)
    {
        var tempPath = Path.Combine(DemoPaths.RepositoryRoot, ".tmp", "coverage-program", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempPath);
        return Path.Combine(tempPath, fileName);
    }
}
