using Oocx.TfPlan2Md.MarkdownGeneration;

namespace Oocx.TfPlan2Md.MarkdownGeneration.Rendering;

/// <summary>
/// Renders the report header section.
/// Related feature: docs/features/107-remove-scriban/specification.md.
/// </summary>
internal sealed class HeaderRenderer
{
    /// <summary>
    /// Default report title when no custom title is specified.
    /// </summary>
    private readonly string _defaultReportTitle;

    /// <summary>
    /// Initializes a new instance of the <see cref="HeaderRenderer"/> class.
    /// </summary>
    /// <param name="defaultReportTitle">Fallback report title.</param>
    public HeaderRenderer(string defaultReportTitle = "Terraform Plan Report")
    {
        _defaultReportTitle = defaultReportTitle;
    }

    /// <summary>
    /// Renders report heading and optional metadata line.
    /// </summary>
    /// <param name="writer">Markdown writer target.</param>
    /// <param name="model">Report model.</param>
    public void Render(MarkdownWriter writer, ReportModel model)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(model);

        var title = model.ReportTitle;
        if (string.IsNullOrWhiteSpace(title))
        {
            title = _defaultReportTitle;
        }

        writer.Heading(MarkdownHelpers.EscapeMarkdownHeading(title), 1);
        writer.BlankLine();

        RenderPlanStatusBanner(writer, model.PlanStatus);

        if (!model.HideMetadata)
        {
            var generatedAt = model.GeneratedAtUtc.UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);

            writer.Paragraph(
                $"Generated by tfplan2md {MarkdownHelpers.EscapeMarkdown(model.TfPlan2MdVersion)} ({MarkdownHelpers.EscapeMarkdown(model.CommitHash)}) on {generatedAt} UTC | Terraform {MarkdownHelpers.EscapeMarkdown(model.TerraformVersion)}");
            writer.BlankLine();
        }
    }

    /// <summary>
    /// Renders a plan-status callout banner immediately after the report title,
    /// only when one or more of the Terraform 1.14+ plan-status booleans signals
    /// a non-ordinary state. Multiple signals are stacked as separate blockquote
    /// lines in a single block. The banner is silent for ordinary applyable+complete+
    /// not-errored plans and for plans that do not carry these fields at all.
    /// Related feature: docs/features/122-terraform-1-15-support/adr-002-h2-report-layout.md.
    /// </summary>
    /// <param name="writer">Markdown writer target.</param>
    /// <param name="status">Plan status model (may be null).</param>
    private static void RenderPlanStatusBanner(MarkdownWriter writer, Models.PlanStatusModel? status)
    {
        if (status is null)
        {
            return;
        }

        var lines = new List<string>(3);
        if (status.Errored == true)
        {
            lines.Add("> 🛑 **Plan errored** — Terraform encountered errors while computing this plan.");
        }

        if (status.Applyable == false)
        {
            lines.Add("> ⛔ **Plan is not applyable** — Terraform refused to apply this plan.");
        }

        if (status.Complete == false)
        {
            lines.Add("> ⚠️ **Plan is incomplete** — this plan does not represent the full intended state.");
        }

        if (lines.Count == 0)
        {
            return;
        }

        foreach (var line in lines)
        {
            writer.Raw(line);
            writer.Raw("\n");
        }

        writer.Raw("\n");
    }
}
