using Oocx.TfPlan2Md.MarkdownGeneration;

namespace Oocx.TfPlan2Md.MarkdownGeneration.Rendering;

/// <summary>
/// Renders the report header section.
/// Related feature: docs/features/107-remove-scriban/specification.md.
/// </summary>
internal sealed class HeaderRenderer
{
    /// <summary>
    /// Default report title when no custom title is specified.
    /// </summary>
    private readonly string _defaultReportTitle;

    /// <summary>
    /// Initializes a new instance of the <see cref="HeaderRenderer"/> class.
    /// </summary>
    /// <param name="defaultReportTitle">Fallback report title.</param>
    public HeaderRenderer(string defaultReportTitle = "Terraform Plan Report")
    {
        _defaultReportTitle = defaultReportTitle;
    }

    /// <summary>
    /// Renders report heading and optional metadata line.
    /// </summary>
    /// <param name="writer">Markdown writer target.</param>
    /// <param name="model">Report model.</param>
    public void Render(MarkdownWriter writer, ReportModel model)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(model);

        var title = model.ReportTitle;
        if (string.IsNullOrWhiteSpace(title))
        {
            title = _defaultReportTitle;
        }

        writer.Heading(MarkdownHelpers.EscapeMarkdownHeading(title), 1);
        writer.BlankLine();

        if (!model.HideMetadata)
        {
            var generatedAt = model.GeneratedAtUtc.UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);

            writer.Paragraph(
                $"Generated by tfplan2md {MarkdownHelpers.EscapeMarkdown(model.TfPlan2MdVersion)} ({MarkdownHelpers.EscapeMarkdown(model.CommitHash)}) on {generatedAt} UTC | Terraform {MarkdownHelpers.EscapeMarkdown(model.TerraformVersion)}");
            writer.BlankLine();
        }
    }
}
