#!/usr/bin/env python3
"""Generate harness adapters from the canonical agent configuration.

Canonical content lives under `.agents/` and is harness-neutral. This script
materialises the Claude Code adapter under `.claude/`:

    .agents/roles/*.md        -> .claude/agents/*.md      (tier resolved to a model)
    .agents/skills/<n>/       -> .claude/skills/<n>/       (verbatim)
    .agents/commands/*.md     -> .claude/commands/*.md     (verbatim)
    .agents/claude-settings.json -> .claude/settings.json  (verbatim)

Edit files under `.agents/`. Never edit the generated files under `.claude/` —
they carry a header saying so and are overwritten on every run.

Usage:
    scripts/sync-agent-config.sh            regenerate the adapter
    scripts/sync-agent-config.sh --check    exit 1 if the adapter is stale (CI)
"""

from __future__ import annotations

import filecmp
import json
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CANON = REPO / ".agents"
CLAUDE = REPO / ".claude"

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/sync-agent-config.sh from {source} — do not edit. -->\n"
)


def fail(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def split_frontmatter(text: str, path: Path) -> tuple[dict[str, str], str]:
    """Return (frontmatter, body). Frontmatter is flat `key: value` YAML."""
    if not text.startswith("---\n"):
        fail(f"{path}: missing YAML frontmatter")
    end = text.find("\n---\n", 3)
    if end == -1:
        fail(f"{path}: unterminated YAML frontmatter")
    meta: dict[str, str] = {}
    for line in text[4:end].splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            fail(f"{path}: frontmatter line is not `key: value`: {line!r}")
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip().strip("\"'")
    return meta, text[end + 5 :]


def load_tiers() -> dict[str, dict[str, str]]:
    data = json.loads((CANON / "tiers.json").read_text(encoding="utf-8"))
    return data["tiers"]


def render_role(path: Path, tiers: dict[str, dict[str, str]]) -> str:
    meta, body = split_frontmatter(path.read_text(encoding="utf-8"), path)

    for required in ("name", "description", "tier"):
        if required not in meta:
            fail(f"{path}: frontmatter is missing `{required}`")

    tier = meta["tier"]
    if tier not in tiers:
        fail(f"{path}: unknown tier {tier!r} (expected one of {', '.join(tiers)})")
    if "model" in meta:
        fail(f"{path}: role files declare `tier`, not `model` — the mapping lives in .agents/tiers.json")

    # The Code Reviewer normally runs in Codex via scripts/codex-review.sh, but it
    # still needs a Claude agent definition for the fallback path taken when codex
    # is absent or fails twice.
    model = tiers[tier]["claude"]

    lines = [
        "---",
        f"name: {meta['name']}",
        f"description: {meta['description']}",
        f"model: {model}",
        "---",
        "",
        GENERATED_HEADER.format(source=f".agents/roles/{path.name}").rstrip(),
    ]
    return "\n".join(lines) + "\n" + body


def sync_roles(tiers: dict[str, dict[str, str]], out: Path) -> int:
    src = CANON / "roles"
    if not src.is_dir():
        return 0
    dest = out / "agents"
    dest.mkdir(parents=True, exist_ok=True)
    count = 0
    for role in sorted(src.glob("*.md")):
        (dest / role.name).write_text(render_role(role, tiers), encoding="utf-8")
        count += 1
    return count


# Two skills vendor npm dependencies. Those are gitignored build artefacts, not
# instructions, and copying them puts tens of thousands of files into the
# adapter and into every agent's search path.
IGNORED = shutil.ignore_patterns(
    "node_modules", "__pycache__", ".git", "*.pyc", "package-lock.json"
)


def sync_tree(name: str, out: Path) -> int:
    """Copy a canonical subdirectory into the adapter, minus build artefacts."""
    src = CANON / name
    if not src.is_dir():
        return 0
    dest = out / name
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest, ignore=IGNORED)
    return sum(1 for _ in dest.rglob("*") if _.is_file())


def sync_settings(out: Path) -> int:
    src = CANON / "claude-settings.json"
    if not src.is_file():
        return 0
    out.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, out / "settings.json")
    return 1


def generate(out: Path) -> dict[str, int]:
    tiers = load_tiers()
    return {
        "roles": sync_roles(tiers, out),
        "skills": sync_tree("skills", out),
        "commands": sync_tree("commands", out),
        "settings": sync_settings(out),
    }


def tree_differs(a: Path, b: Path) -> list[str]:
    """Return paths (relative to a) that differ between two trees."""
    diffs: list[str] = []
    a_files = {p.relative_to(a) for p in a.rglob("*") if p.is_file()}
    b_files = {p.relative_to(b) for p in b.rglob("*") if p.is_file()}
    for rel in sorted(a_files - b_files):
        diffs.append(f"missing in generated: {rel}")
    for rel in sorted(b_files - a_files):
        diffs.append(f"stale, not regenerated: {rel}")
    for rel in sorted(a_files & b_files):
        if not filecmp.cmp(a / rel, b / rel, shallow=False):
            diffs.append(f"differs: {rel}")
    return diffs


def main() -> int:
    check = "--check" in sys.argv[1:]

    if not CANON.is_dir():
        fail(f"{CANON} does not exist — nothing to sync")

    if check:
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            expected = Path(tmp) / "claude"
            generate(expected)
            # Only the directories this script owns are compared; anything else
            # under .claude/ (settings.local.json, for instance) is the user's.
            owned = ["agents", "skills", "commands", "settings.json"]
            diffs: list[str] = []
            for entry in owned:
                want, have = expected / entry, CLAUDE / entry
                if want.is_dir():
                    if not have.is_dir():
                        diffs.append(f"missing in generated: {entry}/")
                    else:
                        diffs += [f"{entry}/{d}" for d in tree_differs(want, have)]
                elif want.is_file():
                    if not have.is_file():
                        diffs.append(f"missing in generated: {entry}")
                    elif not filecmp.cmp(want, have, shallow=False):
                        diffs.append(f"differs: {entry}")

            if diffs:
                print("FAIL: .claude/ is out of date with .agents/")
                for d in diffs:
                    print(f"  {d}")
                print("\nRun scripts/sync-agent-config.sh and commit the result.")
                return 1
            print("OK: .claude/ matches .agents/")
            return 0

    counts = generate(CLAUDE)
    print(
        "Generated .claude/ from .agents/: "
        f"{counts['roles']} role(s), {counts['skills']} skill file(s), "
        f"{counts['commands']} command file(s), {counts['settings']} settings file(s)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
