#!/usr/bin/env bash
# UAT Helper Script for GitHub
# Usage: scripts/uat-github.sh <action> [args]
#
# Actions:
#   create <file>   - Create a UAT PR with initial comment from <file>
#   comment <pr-number> <file> - Add a comment to PR from <file>
#   poll <pr-number> - Poll for new comments and check for approval
#   cleanup <pr-number> - Close the PR after UAT completion

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# Artifact validation implemented in shared helper
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$script_dir/uat-helpers.sh"


cmd_create() {
    local file="${1:-}"
    local simulate="${UAT_SIMULATE:-false}"
    local force="${UAT_FORCE:-false}"
    
    # Validate and potentially set default artifact (platform-aware)
    file="$(validate_artifact github "$file" "$simulate" "$force")"
    
    local branch
    branch=$(git branch --show-current)
    local title="UAT: $(basename "$file" .md)"
    local body
    body=$(cat <<'EOF'
## Problem
Validate markdown rendering in real PR UIs.

## Change
Create a UAT PR and post the test markdown as PR comments.

## Verification
Maintainer visually reviews the PR comment rendering in GitHub.
EOF
)
    
    log_info "Using artifact: $file"
    log_info "Pushing branch to GitHub..."
    git push -u origin HEAD --force
    
    log_info "Creating PR..."
    local pr_url
    pr_url=$(PAGER=cat gh pr create \
        --title "$title" \
        --body "$body" \
        --base main \
        --head "$branch")
    
    local pr_number
    pr_number=$(echo "$pr_url" | grep -oE '[0-9]+$')
    
    log_info "PR created: #$pr_number"
    
    # Add the markdown content as a comment
    log_info "Adding initial UAT content as comment..."
    cmd_comment "$pr_number" "$file"
    
    echo ""
    echo "========================================="
    echo "UAT PR Created: #$pr_number"
    echo "URL: $pr_url"
    echo "========================================="
    echo ""
    echo "Next steps:"
    echo "  1. Maintainer reviews the PR comment in GitHub"
    echo "  2. Poll for feedback: $0 poll $pr_number"
    echo "  3. After approval: $0 cleanup $pr_number"
}

cmd_comment() {
    local pr_number="${1:-}"
    local file="${2:-}"
    
    if [[ -z "$pr_number" || -z "$file" || ! -f "$file" ]]; then
        log_error "Usage: $0 comment <pr-number> <markdown-file>"
        exit 1
    fi
    
    # Prefix comment to distinguish agent-generated content from human comments
    local prefix="🤖 **Copilot Code Reviewer** — _This comment was generated by an AI agent._

---

"
    local content
    content=$(cat "$file")
    
    echo "${prefix}${content}" | PAGER=cat gh pr comment "$pr_number" --body-file -
    log_info "Comment added to PR #$pr_number"
}

cmd_poll() {
    local pr_number="${1:-}"
    
    if [[ -z "$pr_number" ]]; then
        log_error "Usage: $0 poll <pr-number>"
        exit 1
    fi
    
    log_info "Polling comments for PR #$pr_number..."
    
    # Get PR state (structured)
    local pr_state
    pr_state=$(PAGER=cat gh pr view "$pr_number" --json state -q '.state' 2>/dev/null || echo "")
    if [[ -z "$pr_state" ]]; then
        log_error "Failed to read PR state. Ensure gh is authenticated and the PR exists."
        return 2
    fi
    
    if [[ "$pr_state" == "CLOSED" || "$pr_state" == "MERGED" ]]; then
        echo -e "${GREEN}✓ PR CLOSED${NC}"
        echo "PR has been closed by Maintainer. UAT passed."
        return 0
    fi
    
    # Get comments (structured) and check for approval keywords in NON-agent comments.
    # Agent comments include the marker line: "This comment was generated by an AI agent."
    local approval_found
    approval_found=$(PAGER=cat gh pr view "$pr_number" --json comments -q '.comments[]
            | select((.body // "") | contains("This comment was generated by an AI agent.") | not)
            | select((.body // "") | test("(?i)(approved|passed|accept|lgtm)"))
            | .body' 2>/dev/null || true)

    echo ""
    echo "=== Recent Comments (JSON) ==="
    # Show up to the last 3 comments (author + truncated body). Avoid parsing formatted text output.
    PAGER=cat gh pr view "$pr_number" --json comments -q '(
            if (.comments | length) == 0 then
                "(no comments)"
            else
                .comments[-3:][]
                | "[\(.author.login // "unknown")]: \((.body // "") | gsub("\r"; "") | .[0:200])"
            end
        )' 2>/dev/null || echo "(failed to load comments)"
    echo ""
    
    if [[ -n "$approval_found" ]]; then
        echo -e "${GREEN}✓ APPROVAL DETECTED${NC}"
        echo "Approval keyword found in comments. UAT passed."
        return 0
    fi
    
    echo -e "${YELLOW}⏳ AWAITING FEEDBACK${NC}"
    echo "No approval detected yet. Continue polling or check GitHub UI."
    return 1
}

cmd_cleanup() {
    local pr_number="${1:-}"
    
    if [[ -z "$pr_number" ]]; then
        log_error "Usage: $0 cleanup <pr-number>"
        exit 1
    fi
    
    log_info "Closing PR #$pr_number..."
    # Note: Do NOT use --delete-branch here. Branch deletion causes immediate
    # checkout to main, which breaks subsequent commands that need scripts.
    # Delete branches manually after both cleanups complete.
    PAGER=cat gh pr close "$pr_number" || log_warn "PR may already be closed"
    
    log_info "Cleanup complete. Remember to delete the remote branch manually."
}

# Main dispatch
action="${1:-}"
shift || true

case "$action" in
    create)  cmd_create "$@" ;;
    comment) cmd_comment "$@" ;;
    poll)    cmd_poll "$@" ;;
    cleanup) cmd_cleanup "$@" ;;
    *)
        echo "UAT Helper Script for GitHub"
        echo ""
        echo "Usage: $0 <action> [args]"
        echo ""
        echo "Actions:"
        echo "  create <file>   - Create a UAT PR with initial comment from <file>"
        echo "  comment <pr-number> <file> - Add a comment to PR from <file>"
        echo "  poll <pr-number> - Poll for new comments and check for approval"
        echo "  cleanup <pr-number> - Close the PR after UAT completion"
        exit 1
        ;;
esac
