using System.IO;
using Oocx.TfPlan2Md.CodeAnalysis;
using Oocx.TfPlan2Md.MarkdownGeneration;
using Oocx.TfPlan2Md.MarkdownGeneration.Services;
using Oocx.TfPlan2Md.MarkdownGeneration.Summaries;
using Oocx.TfPlan2Md.Parsing;
using Oocx.TfPlan2Md.Platforms.Azure;
using Oocx.TfPlan2Md.Providers;
using Oocx.TfPlan2Md.Providers.AzApi;
using Oocx.TfPlan2Md.Providers.AzureAD;
using Oocx.TfPlan2Md.Providers.AzureDevOps;
using Oocx.TfPlan2Md.Providers.AzureRM;
using Oocx.TfPlan2Md.Tests.TestData;
using TUnit.Core;

namespace Oocx.TfPlan2Md.Tests.MarkdownGeneration;

/// <summary>
/// Snapshot (golden file) tests that detect unexpected changes in markdown output.
/// These tests compare the current output against a previously approved baseline,
/// catching subtle regressions that other tests might miss.
/// </summary>
/// <remarks>
/// Snapshot testing works by:
/// 1. Generating markdown output from a fixed input
/// 2. Comparing against a stored "golden" file
/// 3. Failing if there are any differences
/// 
/// When intentional changes are made, developers update the snapshot files.
/// This provides a safety net against accidental output changes.
/// 
/// The snapshots directory stores the expected outputs, organized by test name.
/// </remarks>
public class MarkdownSnapshotTests
{
    private readonly TerraformPlanParser _parser = new();

    /// <summary>
    /// Verifies the comprehensive demo output matches the approved snapshot.
    /// </summary>
    [Test]
    public void Snapshot_ComprehensiveDemo_MatchesBaseline()
    {
        var plan = _parser.Parse(File.ReadAllText(DemoPaths.DemoPlanPath));
        var mappingResult = AzureMappingFileLoader.Load(DemoPaths.DemoPrincipalsPath, diagnosticContext: null);
        var principalMapper = new PrincipalMapper(mappingResult.Principals, mappingResult.PrincipalTypes, diagnosticContext: null);
        var entityMapper = new AzureEntityMapper(
            mappingResult.Subscriptions,
            mappingResult.ManagementGroups,
            mappingResult.Tenants,
            diagnosticContext: null);
        var scopeFormatter = new EnrichedAzureScopeFormatter(entityMapper);
        var providerRegistry = CreateProviderRegistry(principalMapper, scopeFormatter);
        var model = new ReportModelBuilder(
            principalMapper: principalMapper,
            metadataProvider: TestMetadataProvider.Instance,
            providerRegistry: providerRegistry).Build(plan);
        var renderer = new MarkdownRenderer(providerRegistry: providerRegistry);

        var markdown = renderer.Render(model);

        SnapshotTestAssertions.AssertNoEmojiFollowedByRegularSpace(markdown, "comprehensive-demo.md");
        SnapshotTestAssertions.AssertMatchesSnapshot("comprehensive-demo.md", markdown);
    }

    /// <summary>
    /// Verifies the comprehensive demo with ALL features matches the approved snapshot.
    /// This test mirrors the full production flow including all providers, code analysis,
    /// and principal/entity mappings — exactly as generated by generate-demo-artifacts.sh.
    /// </summary>
    [Test]
    public void Snapshot_ComprehensiveDemoFull_MatchesBaseline()
    {
        var plan = _parser.Parse(File.ReadAllText(DemoPaths.DemoPlanPath));

        // Load principal and entity mappings
        var mappingResult = AzureMappingFileLoader.Load(DemoPaths.DemoPrincipalsPath, diagnosticContext: null);
        var principalMapper = new PrincipalMapper(mappingResult.Principals, mappingResult.PrincipalTypes, diagnosticContext: null);
        var entityMapper = new AzureEntityMapper(
            mappingResult.Subscriptions,
            mappingResult.ManagementGroups,
            mappingResult.Tenants,
            diagnosticContext: null);
        var scopeFormatter = new EnrichedAzureScopeFormatter(entityMapper);

        // Register ALL providers (matching ProgramEntry.cs)
        var providerRegistry = new ProviderRegistry();
        providerRegistry.RegisterProvider(new AzApiModule(scopeFormatter));
        providerRegistry.RegisterProvider(new AzureADModule());
        providerRegistry.RegisterProvider(new AzureRMModule(
            largeValueFormat: LargeValueFormat.InlineDiff,
            principalMapper: principalMapper,
            scopeFormatter: scopeFormatter));
        providerRegistry.RegisterProvider(new AzureDevOpsModule());
        var providerContributions = providerRegistry.CreateContributionSet();

        var valueFormatterRegistry = providerContributions.CreateValueFormatterRegistry();
        var iconProviderRegistry = providerContributions.CreateIconProviderRegistry();

        // Load SARIF code analysis results
        var sarifLoader = new CodeAnalysisLoader(new SarifParser());
        var sarifPatterns = new[] { Path.Combine(DemoPaths.StaticAnalysisDirectory, "*.sarif") };
        var loadResult = sarifLoader.Load(sarifPatterns);
        var codeAnalysisInput = new CodeAnalysisInput
        {
            Model = loadResult.Model,
            Warnings = loadResult.Warnings,
            MinimumLevel = null,
            FailOnLevel = null
        };

        // Build model with all features enabled
        var model = new ReportModelBuilder(
            summaryBuilder: new ResourceSummaryBuilder(valueFormatterRegistry),
            principalMapper: principalMapper,
            metadataProvider: TestMetadataProvider.Instance,
            providerRegistry: providerRegistry,
            providerContributions: providerContributions,
            codeAnalysisInput: codeAnalysisInput,
            iconProviderRegistry: iconProviderRegistry).Build(plan);

        // Render with all providers
        var renderer = new MarkdownRenderer(
            providerRegistry: providerRegistry,
            providerContributions: providerContributions,
            valueFormatterRegistry: valueFormatterRegistry,
            iconProviderRegistry: iconProviderRegistry);

        var markdown = renderer.Render(model);

        SnapshotTestAssertions.AssertNoEmojiFollowedByRegularSpace(markdown, "comprehensive-demo-full.md");
        SnapshotTestAssertions.AssertMatchesSnapshot("comprehensive-demo-full.md", markdown);
    }

    /// <summary>
    /// Verifies the summary template output matches the approved snapshot.
    /// </summary>
    [Test]
    public void Snapshot_SummaryTemplate_MatchesBaseline()
    {
        var plan = _parser.Parse(File.ReadAllText(DemoPaths.DemoPlanPath));
        var providerRegistry = CreateProviderRegistry();
        var model = new ReportModelBuilder(
            metadataProvider: TestMetadataProvider.Instance,
            providerRegistry: providerRegistry).Build(plan);
        var renderer = new MarkdownRenderer(providerRegistry: providerRegistry);

        var markdown = renderer.Render(model, "summary");

        SnapshotTestAssertions.AssertNoEmojiFollowedByRegularSpace(markdown, "summary-template.md");
        SnapshotTestAssertions.AssertMatchesSnapshot("summary-template.md", markdown);
    }

    /// <summary>
    /// Verifies the breaking plan output matches the approved snapshot.
    /// This ensures escaping behavior is consistent.
    /// </summary>
    [Test]
    public void Snapshot_BreakingPlan_MatchesBaseline()
    {
        var json = File.ReadAllText("TestData/markdown-breaking-plan.json");
        var plan = _parser.Parse(json);
        var providerRegistry = CreateProviderRegistry();
        var model = new ReportModelBuilder(
            metadataProvider: TestMetadataProvider.Instance,
            providerRegistry: providerRegistry).Build(plan);
        var renderer = new MarkdownRenderer(providerRegistry: providerRegistry);

        var markdown = renderer.Render(model);

        SnapshotTestAssertions.AssertNoEmojiFollowedByRegularSpace(markdown, "breaking-plan.md");
        SnapshotTestAssertions.AssertMatchesSnapshot("breaking-plan.md", markdown);
    }

    /// <summary>
    /// Verifies role assignment rendering matches the approved snapshot.
    /// </summary>
    [Test]
    public void Snapshot_RoleAssignments_MatchesBaseline()
    {
        var json = File.ReadAllText("TestData/role-assignments.json");
        var plan = _parser.Parse(json);
        var mappingResult = AzureMappingFileLoader.Load(DemoPaths.DemoPrincipalsPath, diagnosticContext: null);
        var principalMapper = new PrincipalMapper(mappingResult.Principals, mappingResult.PrincipalTypes, diagnosticContext: null);
        var entityMapper = new AzureEntityMapper(
            mappingResult.Subscriptions,
            mappingResult.ManagementGroups,
            mappingResult.Tenants,
            diagnosticContext: null);
        var scopeFormatter = new EnrichedAzureScopeFormatter(entityMapper);
        var providerRegistry = CreateProviderRegistry(principalMapper, scopeFormatter);
        var model = new ReportModelBuilder(
            principalMapper: principalMapper,
            metadataProvider: TestMetadataProvider.Instance,
            providerRegistry: providerRegistry).Build(plan);
        var renderer = new MarkdownRenderer(providerRegistry: providerRegistry);

        var markdown = renderer.Render(model);

        SnapshotTestAssertions.AssertNoEmojiFollowedByRegularSpace(markdown, "role-assignments.md");
        SnapshotTestAssertions.AssertMatchesSnapshot("role-assignments.md", markdown);
    }

    /// <summary>
    /// Verifies Azure display enhancements rendering matches the approved snapshot.
    /// </summary>
    [Test]
    public void Snapshot_AzureDisplayEnhancements_MatchesBaseline()
    {
        var json = File.ReadAllText("TestData/azure-display-enhancements.json");
        var plan = _parser.Parse(json);

        var mappingResult = AzureMappingFileLoader.Load("TestData/azure-mappings-extended.json", diagnosticContext: null);
        var roleDefinitionResolver = new AzureRoleDefinitionResolver(mappingResult.Roles, diagnosticContext: null);

        var principalMapper = new PrincipalMapper(mappingResult.Principals, mappingResult.PrincipalTypes, diagnosticContext: null);
        var entityMapper = new AzureEntityMapper(
            mappingResult.Subscriptions,
            mappingResult.ManagementGroups,
            mappingResult.Tenants,
            diagnosticContext: null);
        var scopeFormatter = new EnrichedAzureScopeFormatter(entityMapper);
        var providerRegistry = CreateProviderRegistry(principalMapper, scopeFormatter, roleDefinitionResolver);

        var model = new ReportModelBuilder(
            metadataProvider: TestMetadataProvider.Instance,
            providerRegistry: providerRegistry).Build(plan);
        var renderer = new MarkdownRenderer(providerRegistry: providerRegistry);

        var markdown = renderer.Render(model);

        SnapshotTestAssertions.AssertNoEmojiFollowedByRegularSpace(markdown, "azure-display-enhancements.md");
        SnapshotTestAssertions.AssertMatchesSnapshot("azure-display-enhancements.md", markdown);
    }

    /// <summary>
    /// Verifies firewall rule rendering matches the approved snapshot.
    /// </summary>
    [Test]
    public void Snapshot_FirewallRules_MatchesBaseline()
    {
        var json = File.ReadAllText("TestData/firewall-rule-changes.json");
        var plan = _parser.Parse(json);
        var providerRegistry = CreateProviderRegistry();
        var model = new ReportModelBuilder(
            metadataProvider: TestMetadataProvider.Instance,
            providerRegistry: providerRegistry).Build(plan);
        var renderer = new MarkdownRenderer(providerRegistry: providerRegistry);

        var markdown = renderer.Render(model);

        SnapshotTestAssertions.AssertNoEmojiFollowedByRegularSpace(markdown, "firewall-rules.md");
        SnapshotTestAssertions.AssertMatchesSnapshot("firewall-rules.md", markdown);
    }

    /// <summary>
    /// Verifies multi-module plan rendering matches the approved snapshot.
    /// </summary>
    [Test]
    public void Snapshot_MultiModule_MatchesBaseline()
    {
        var json = File.ReadAllText("TestData/multi-module-plan.json");
        var plan = _parser.Parse(json);
        var providerRegistry = CreateProviderRegistry();
        var model = new ReportModelBuilder(
            metadataProvider: TestMetadataProvider.Instance,
            providerRegistry: providerRegistry).Build(plan);
        var renderer = new MarkdownRenderer(providerRegistry: providerRegistry);

        var markdown = renderer.Render(model);

        SnapshotTestAssertions.AssertNoEmojiFollowedByRegularSpace(markdown, "multi-module.md");
        SnapshotTestAssertions.AssertMatchesSnapshot("multi-module.md", markdown);
    }

    /// <summary>
    /// Verifies refactoring summary rendering matches the approved snapshot.
    /// </summary>
    [Test]
    public void Snapshot_RefactoringSummary_MatchesBaseline()
    {
        var json = File.ReadAllText("TestData/refactoring-comprehensive.json");
        var plan = _parser.Parse(json);
        var providerRegistry = CreateProviderRegistry();
        var model = new ReportModelBuilder(
            metadataProvider: TestMetadataProvider.Instance,
            providerRegistry: providerRegistry).Build(plan);
        var renderer = new MarkdownRenderer(providerRegistry: providerRegistry);

        var markdown = renderer.Render(model);

        SnapshotTestAssertions.AssertNoEmojiFollowedByRegularSpace(markdown, "refactoring-comprehensive.md");
        SnapshotTestAssertions.AssertMatchesSnapshot("refactoring-comprehensive.md", markdown);
    }

    /// <summary>
    /// Creates a ProviderRegistry with AzureRM module for testing.
    /// </summary>
    private static ProviderRegistry CreateProviderRegistry(
        IPrincipalMapper? principalMapper = null,
        EnrichedAzureScopeFormatter? scopeFormatter = null,
        IRoleDefinitionResolver? roleDefinitionResolver = null)
    {
        var registry = new ProviderRegistry();
        registry.RegisterProvider(new AzureRMModule(
            largeValueFormat: LargeValueFormat.InlineDiff,
            principalMapper: principalMapper,
            scopeFormatter: scopeFormatter,
            roleDefinitionResolver: roleDefinitionResolver));
        return registry;
    }
}
