#!/usr/bin/env bash
# protect-changelog.sh - GitHub Copilot preToolUse hook.
#
# Denies any attempt to directly edit or create CHANGELOG.md. CHANGELOG.md is
# auto-generated by Versionize in the CI pipeline after the Release Manager
# creates and merges the PR. Agents must never edit it manually.
#
# If the changelog is missing or outdated, invoke the Release Manager agent to
# create and merge the PR, which triggers CI and runs Versionize automatically.
#
# Input (stdin): JSON with fields: toolName, toolArgs
# Output:        JSON permissionDecision when denying; nothing otherwise (exit 0)

set -euo pipefail

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.toolName')

# Only intercept file-writing tools
if [[ "$TOOL_NAME" != "edit" && "$TOOL_NAME" != "create" ]]; then
  exit 0
fi

# Extract the file path from tool arguments
FILE_PATH=$(echo "$INPUT" | jq -r '.toolArgs | fromjson | .path // empty' 2>/dev/null || true)

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

# Check if the target file is CHANGELOG.md (matches both ./CHANGELOG.md and CHANGELOG.md)
if [[ "$FILE_PATH" == *"CHANGELOG.md" ]]; then
  jq -cn '{
    permissionDecision: "deny",
    permissionDecisionReason: "CHANGELOG.md must not be edited manually. It is auto-generated by Versionize in the CI pipeline after the Release Manager creates and merges the PR. If the changelog is missing or out of date, invoke the Release Manager agent to create the PR and trigger CI — Versionize will update CHANGELOG.md automatically after merge."
  }'
fi
